version: "3"

services:
  http:
    build: .
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    depends_on:
      - db
    networks:
      - internal
  db:
    image: postgres:14-alpine
    volumes:
      - "/var/lib/postgresql/bukit_vista/data:/var/lib/postgresql/data"
    ports:
      - "${PGPORT}:5432"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    networks:
      - internal

networks:
  internal:
    driver: bridge
